spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mtdz9999.cj4i4xwwgtd2.ap-northeast-2.rds.amazonaws.com:3306/rtdc?serverTimezone=Asia/Seoul
    #url: jdbc:mariadb://database:3306/rtdc?serverTimezone=Asia/Seoul
    username: mtdz9999
    password: mtdz9999tothemoon
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      #location: C:/images 
      max-file-size: 10MB
      max-request-size: 10MB
custom:
  upload-img-path: /home/ec2-user/RTDC/upload-file/
  raffle-img-path: /home/ec2-user/RTDC/raffle-file/
  profile-img-path: /home/ec2-user/RTDC/profile-file/
  #upload-img-path: c:/dev/WORKSPACE/RTDC/upload-file/
  #event-img-path: c:/dev/WORKSPACE/RTDC/event-file/
  #profile-img-path: c:/dev/WORKSPACE/RTDC/profile-file/